#!/bin/sh
#PBS -l nodes=2:ppn=16,feature=16core,mem=100gb,walltime=00:01:00:00
#PBS -j oe
#PBS -o /usr/lusers/rodluger/src/hyaktest/test.log
#PBS -m abe

## This prevents numpy from multithreading. See http://stackoverflow.com/a/19258728
## Note that this is specific to numpy versions linked with OpenBLAS
export OPENBLAS_NUM_THREADS=1

cd /usr/lusers/rodluger/src/hyaktest

mpirun -np $PBS_NP python test.py
